#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaoDucPhoCap
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="GiaoDucPhoCap")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttbChuHo(tbChuHo instance);
    partial void UpdatetbChuHo(tbChuHo instance);
    partial void DeletetbChuHo(tbChuHo instance);
    partial void InserttbCSVC(tbCSVC instance);
    partial void UpdatetbCSVC(tbCSVC instance);
    partial void DeletetbCSVC(tbCSVC instance);
    partial void InserttbGiaoVien(tbGiaoVien instance);
    partial void UpdatetbGiaoVien(tbGiaoVien instance);
    partial void DeletetbGiaoVien(tbGiaoVien instance);
    partial void InserttbHuyen(tbHuyen instance);
    partial void UpdatetbHuyen(tbHuyen instance);
    partial void DeletetbHuyen(tbHuyen instance);
    partial void InserttbLopHoc(tbLopHoc instance);
    partial void UpdatetbLopHoc(tbLopHoc instance);
    partial void DeletetbLopHoc(tbLopHoc instance);
    partial void InserttbThanhVien(tbThanhVien instance);
    partial void UpdatetbThanhVien(tbThanhVien instance);
    partial void DeletetbThanhVien(tbThanhVien instance);
    partial void InserttbThonXom(tbThonXom instance);
    partial void UpdatetbThonXom(tbThonXom instance);
    partial void DeletetbThonXom(tbThonXom instance);
    partial void InserttbTinh(tbTinh instance);
    partial void UpdatetbTinh(tbTinh instance);
    partial void DeletetbTinh(tbTinh instance);
    partial void InserttbTruong(tbTruong instance);
    partial void UpdatetbTruong(tbTruong instance);
    partial void DeletetbTruong(tbTruong instance);
    partial void InserttbXa(tbXa instance);
    partial void UpdatetbXa(tbXa instance);
    partial void DeletetbXa(tbXa instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::GiaoDucPhoCap.Properties.Settings.Default.GiaoDucPhoCapConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbChuHo> tbChuHos
		{
			get
			{
				return this.GetTable<tbChuHo>();
			}
		}
		
		public System.Data.Linq.Table<tbCSVC> tbCSVCs
		{
			get
			{
				return this.GetTable<tbCSVC>();
			}
		}
		
		public System.Data.Linq.Table<tbGiaoVien> tbGiaoViens
		{
			get
			{
				return this.GetTable<tbGiaoVien>();
			}
		}
		
		public System.Data.Linq.Table<tbHuyen> tbHuyens
		{
			get
			{
				return this.GetTable<tbHuyen>();
			}
		}
		
		public System.Data.Linq.Table<tbLopHoc> tbLopHocs
		{
			get
			{
				return this.GetTable<tbLopHoc>();
			}
		}
		
		public System.Data.Linq.Table<tbThanhVien> tbThanhViens
		{
			get
			{
				return this.GetTable<tbThanhVien>();
			}
		}
		
		public System.Data.Linq.Table<tbThonXom> tbThonXoms
		{
			get
			{
				return this.GetTable<tbThonXom>();
			}
		}
		
		public System.Data.Linq.Table<tbTinh> tbTinhs
		{
			get
			{
				return this.GetTable<tbTinh>();
			}
		}
		
		public System.Data.Linq.Table<tbTruong> tbTruongs
		{
			get
			{
				return this.GetTable<tbTruong>();
			}
		}
		
		public System.Data.Linq.Table<tbXa> tbXas
		{
			get
			{
				return this.GetTable<tbXa>();
			}
		}
	}
	
	[Table(Name="dbo.tbChuHo")]
	public partial class tbChuHo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHoGiaDinh;
		
		private string _MaThon;
		
		private string _TenChuHo;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _GioiTinh;
		
		private string _DanToc;
		
		private EntitySet<tbThanhVien> _tbThanhViens;
		
		private EntityRef<tbThonXom> _tbThonXom;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoGiaDinhChanging(string value);
    partial void OnMaHoGiaDinhChanged();
    partial void OnMaThonChanging(string value);
    partial void OnMaThonChanged();
    partial void OnTenChuHoChanging(string value);
    partial void OnTenChuHoChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnDanTocChanging(string value);
    partial void OnDanTocChanged();
    #endregion
		
		public tbChuHo()
		{
			this._tbThanhViens = new EntitySet<tbThanhVien>(new Action<tbThanhVien>(this.attach_tbThanhViens), new Action<tbThanhVien>(this.detach_tbThanhViens));
			this._tbThonXom = default(EntityRef<tbThonXom>);
			OnCreated();
		}
		
		[Column(Storage="_MaHoGiaDinh", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHoGiaDinh
		{
			get
			{
				return this._MaHoGiaDinh;
			}
			set
			{
				if ((this._MaHoGiaDinh != value))
				{
					this.OnMaHoGiaDinhChanging(value);
					this.SendPropertyChanging();
					this._MaHoGiaDinh = value;
					this.SendPropertyChanged("MaHoGiaDinh");
					this.OnMaHoGiaDinhChanged();
				}
			}
		}
		
		[Column(Storage="_MaThon", DbType="NChar(10)")]
		public string MaThon
		{
			get
			{
				return this._MaThon;
			}
			set
			{
				if ((this._MaThon != value))
				{
					if (this._tbThonXom.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaThonChanging(value);
					this.SendPropertyChanging();
					this._MaThon = value;
					this.SendPropertyChanged("MaThon");
					this.OnMaThonChanged();
				}
			}
		}
		
		[Column(Storage="_TenChuHo", DbType="NVarChar(100)")]
		public string TenChuHo
		{
			get
			{
				return this._TenChuHo;
			}
			set
			{
				if ((this._TenChuHo != value))
				{
					this.OnTenChuHoChanging(value);
					this.SendPropertyChanging();
					this._TenChuHo = value;
					this.SendPropertyChanged("TenChuHo");
					this.OnTenChuHoChanged();
				}
			}
		}
		
		[Column(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[Column(Storage="_GioiTinh", DbType="NVarChar(5)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[Column(Storage="_DanToc", DbType="NVarChar(50)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this.OnDanTocChanging(value);
					this.SendPropertyChanging();
					this._DanToc = value;
					this.SendPropertyChanged("DanToc");
					this.OnDanTocChanged();
				}
			}
		}
		
		[Association(Name="tbChuHo_tbThanhVien", Storage="_tbThanhViens", OtherKey="MaHoGiaDinh")]
		public EntitySet<tbThanhVien> tbThanhViens
		{
			get
			{
				return this._tbThanhViens;
			}
			set
			{
				this._tbThanhViens.Assign(value);
			}
		}
		
		[Association(Name="tbThonXom_tbChuHo", Storage="_tbThonXom", ThisKey="MaThon", IsForeignKey=true)]
		public tbThonXom tbThonXom
		{
			get
			{
				return this._tbThonXom.Entity;
			}
			set
			{
				tbThonXom previousValue = this._tbThonXom.Entity;
				if (((previousValue != value) 
							|| (this._tbThonXom.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbThonXom.Entity = null;
						previousValue.tbChuHos.Remove(this);
					}
					this._tbThonXom.Entity = value;
					if ((value != null))
					{
						value.tbChuHos.Add(this);
						this._MaThon = value.MaThon;
					}
					else
					{
						this._MaThon = default(string);
					}
					this.SendPropertyChanged("tbThonXom");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbThanhViens(tbThanhVien entity)
		{
			this.SendPropertyChanging();
			entity.tbChuHo = this;
		}
		
		private void detach_tbThanhViens(tbThanhVien entity)
		{
			this.SendPropertyChanging();
			entity.tbChuHo = null;
		}
	}
	
	[Table(Name="dbo.tbCSVC")]
	public partial class tbCSVC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCSVC;
		
		private string _TenCSVC;
		
		private System.Nullable<int> _SoLuong;
		
		private string _GhiChu;
		
		private string _MaTruong;
		
		private EntityRef<tbTruong> _tbTruong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCSVCChanging(string value);
    partial void OnMaCSVCChanged();
    partial void OnTenCSVCChanging(string value);
    partial void OnTenCSVCChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnMaTruongChanging(string value);
    partial void OnMaTruongChanged();
    #endregion
		
		public tbCSVC()
		{
			this._tbTruong = default(EntityRef<tbTruong>);
			OnCreated();
		}
		
		[Column(Storage="_MaCSVC", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCSVC
		{
			get
			{
				return this._MaCSVC;
			}
			set
			{
				if ((this._MaCSVC != value))
				{
					this.OnMaCSVCChanging(value);
					this.SendPropertyChanging();
					this._MaCSVC = value;
					this.SendPropertyChanged("MaCSVC");
					this.OnMaCSVCChanged();
				}
			}
		}
		
		[Column(Storage="_TenCSVC", DbType="NVarChar(50)")]
		public string TenCSVC
		{
			get
			{
				return this._TenCSVC;
			}
			set
			{
				if ((this._TenCSVC != value))
				{
					this.OnTenCSVCChanging(value);
					this.SendPropertyChanging();
					this._TenCSVC = value;
					this.SendPropertyChanged("TenCSVC");
					this.OnTenCSVCChanged();
				}
			}
		}
		
		[Column(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[Column(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[Column(Storage="_MaTruong", DbType="NChar(10)")]
		public string MaTruong
		{
			get
			{
				return this._MaTruong;
			}
			set
			{
				if ((this._MaTruong != value))
				{
					if (this._tbTruong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTruongChanging(value);
					this.SendPropertyChanging();
					this._MaTruong = value;
					this.SendPropertyChanged("MaTruong");
					this.OnMaTruongChanged();
				}
			}
		}
		
		[Association(Name="tbTruong_tbCSVC", Storage="_tbTruong", ThisKey="MaTruong", IsForeignKey=true)]
		public tbTruong tbTruong
		{
			get
			{
				return this._tbTruong.Entity;
			}
			set
			{
				tbTruong previousValue = this._tbTruong.Entity;
				if (((previousValue != value) 
							|| (this._tbTruong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbTruong.Entity = null;
						previousValue.tbCSVCs.Remove(this);
					}
					this._tbTruong.Entity = value;
					if ((value != null))
					{
						value.tbCSVCs.Add(this);
						this._MaTruong = value.MaTruong;
					}
					else
					{
						this._MaTruong = default(string);
					}
					this.SendPropertyChanged("tbTruong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.tbGiaoVien")]
	public partial class tbGiaoVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGiaoVien;
		
		private string _TenGiaoVien;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _GioiTinh;
		
		private string _ChucVu;
		
		private string _ChuyenNganh;
		
		private string _TinhTrangCongTac;
		
		private string _DangDayLop;
		
		private System.Nullable<int> _SoTietDay;
		
		private string _XepLoaiGiaoVien;
		
		private string _TrinhDo;
		
		private string _DanToc;
		
		private string _MaTruong;
		
		private EntityRef<tbTruong> _tbTruong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGiaoVienChanging(string value);
    partial void OnMaGiaoVienChanged();
    partial void OnTenGiaoVienChanging(string value);
    partial void OnTenGiaoVienChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    partial void OnChuyenNganhChanging(string value);
    partial void OnChuyenNganhChanged();
    partial void OnTinhTrangCongTacChanging(string value);
    partial void OnTinhTrangCongTacChanged();
    partial void OnDangDayLopChanging(string value);
    partial void OnDangDayLopChanged();
    partial void OnSoTietDayChanging(System.Nullable<int> value);
    partial void OnSoTietDayChanged();
    partial void OnXepLoaiGiaoVienChanging(string value);
    partial void OnXepLoaiGiaoVienChanged();
    partial void OnTrinhDoChanging(string value);
    partial void OnTrinhDoChanged();
    partial void OnDanTocChanging(string value);
    partial void OnDanTocChanged();
    partial void OnMaTruongChanging(string value);
    partial void OnMaTruongChanged();
    #endregion
		
		public tbGiaoVien()
		{
			this._tbTruong = default(EntityRef<tbTruong>);
			OnCreated();
		}
		
		[Column(Storage="_MaGiaoVien", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGiaoVien
		{
			get
			{
				return this._MaGiaoVien;
			}
			set
			{
				if ((this._MaGiaoVien != value))
				{
					this.OnMaGiaoVienChanging(value);
					this.SendPropertyChanging();
					this._MaGiaoVien = value;
					this.SendPropertyChanged("MaGiaoVien");
					this.OnMaGiaoVienChanged();
				}
			}
		}
		
		[Column(Storage="_TenGiaoVien", DbType="NVarChar(100)")]
		public string TenGiaoVien
		{
			get
			{
				return this._TenGiaoVien;
			}
			set
			{
				if ((this._TenGiaoVien != value))
				{
					this.OnTenGiaoVienChanging(value);
					this.SendPropertyChanging();
					this._TenGiaoVien = value;
					this.SendPropertyChanged("TenGiaoVien");
					this.OnTenGiaoVienChanged();
				}
			}
		}
		
		[Column(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[Column(Storage="_GioiTinh", DbType="NVarChar(5)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[Column(Storage="_ChucVu", DbType="NVarChar(50)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[Column(Storage="_ChuyenNganh", DbType="NVarChar(50)")]
		public string ChuyenNganh
		{
			get
			{
				return this._ChuyenNganh;
			}
			set
			{
				if ((this._ChuyenNganh != value))
				{
					this.OnChuyenNganhChanging(value);
					this.SendPropertyChanging();
					this._ChuyenNganh = value;
					this.SendPropertyChanged("ChuyenNganh");
					this.OnChuyenNganhChanged();
				}
			}
		}
		
		[Column(Storage="_TinhTrangCongTac", DbType="NVarChar(50)")]
		public string TinhTrangCongTac
		{
			get
			{
				return this._TinhTrangCongTac;
			}
			set
			{
				if ((this._TinhTrangCongTac != value))
				{
					this.OnTinhTrangCongTacChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangCongTac = value;
					this.SendPropertyChanged("TinhTrangCongTac");
					this.OnTinhTrangCongTacChanged();
				}
			}
		}
		
		[Column(Storage="_DangDayLop", DbType="NVarChar(50)")]
		public string DangDayLop
		{
			get
			{
				return this._DangDayLop;
			}
			set
			{
				if ((this._DangDayLop != value))
				{
					this.OnDangDayLopChanging(value);
					this.SendPropertyChanging();
					this._DangDayLop = value;
					this.SendPropertyChanged("DangDayLop");
					this.OnDangDayLopChanged();
				}
			}
		}
		
		[Column(Storage="_SoTietDay", DbType="Int")]
		public System.Nullable<int> SoTietDay
		{
			get
			{
				return this._SoTietDay;
			}
			set
			{
				if ((this._SoTietDay != value))
				{
					this.OnSoTietDayChanging(value);
					this.SendPropertyChanging();
					this._SoTietDay = value;
					this.SendPropertyChanged("SoTietDay");
					this.OnSoTietDayChanged();
				}
			}
		}
		
		[Column(Storage="_XepLoaiGiaoVien", DbType="NVarChar(50)")]
		public string XepLoaiGiaoVien
		{
			get
			{
				return this._XepLoaiGiaoVien;
			}
			set
			{
				if ((this._XepLoaiGiaoVien != value))
				{
					this.OnXepLoaiGiaoVienChanging(value);
					this.SendPropertyChanging();
					this._XepLoaiGiaoVien = value;
					this.SendPropertyChanged("XepLoaiGiaoVien");
					this.OnXepLoaiGiaoVienChanged();
				}
			}
		}
		
		[Column(Storage="_TrinhDo", DbType="NVarChar(50)")]
		public string TrinhDo
		{
			get
			{
				return this._TrinhDo;
			}
			set
			{
				if ((this._TrinhDo != value))
				{
					this.OnTrinhDoChanging(value);
					this.SendPropertyChanging();
					this._TrinhDo = value;
					this.SendPropertyChanged("TrinhDo");
					this.OnTrinhDoChanged();
				}
			}
		}
		
		[Column(Storage="_DanToc", DbType="NVarChar(50)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this.OnDanTocChanging(value);
					this.SendPropertyChanging();
					this._DanToc = value;
					this.SendPropertyChanged("DanToc");
					this.OnDanTocChanged();
				}
			}
		}
		
		[Column(Storage="_MaTruong", DbType="NChar(10)")]
		public string MaTruong
		{
			get
			{
				return this._MaTruong;
			}
			set
			{
				if ((this._MaTruong != value))
				{
					if (this._tbTruong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTruongChanging(value);
					this.SendPropertyChanging();
					this._MaTruong = value;
					this.SendPropertyChanged("MaTruong");
					this.OnMaTruongChanged();
				}
			}
		}
		
		[Association(Name="tbTruong_tbGiaoVien", Storage="_tbTruong", ThisKey="MaTruong", IsForeignKey=true)]
		public tbTruong tbTruong
		{
			get
			{
				return this._tbTruong.Entity;
			}
			set
			{
				tbTruong previousValue = this._tbTruong.Entity;
				if (((previousValue != value) 
							|| (this._tbTruong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbTruong.Entity = null;
						previousValue.tbGiaoViens.Remove(this);
					}
					this._tbTruong.Entity = value;
					if ((value != null))
					{
						value.tbGiaoViens.Add(this);
						this._MaTruong = value.MaTruong;
					}
					else
					{
						this._MaTruong = default(string);
					}
					this.SendPropertyChanged("tbTruong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.tbHuyen")]
	public partial class tbHuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHuyen;
		
		private string _MaTinh;
		
		private string _TenHuyen;
		
		private EntitySet<tbXa> _tbXas;
		
		private EntityRef<tbTinh> _tbTinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHuyenChanging(string value);
    partial void OnMaHuyenChanged();
    partial void OnMaTinhChanging(string value);
    partial void OnMaTinhChanged();
    partial void OnTenHuyenChanging(string value);
    partial void OnTenHuyenChanged();
    #endregion
		
		public tbHuyen()
		{
			this._tbXas = new EntitySet<tbXa>(new Action<tbXa>(this.attach_tbXas), new Action<tbXa>(this.detach_tbXas));
			this._tbTinh = default(EntityRef<tbTinh>);
			OnCreated();
		}
		
		[Column(Storage="_MaHuyen", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHuyen
		{
			get
			{
				return this._MaHuyen;
			}
			set
			{
				if ((this._MaHuyen != value))
				{
					this.OnMaHuyenChanging(value);
					this.SendPropertyChanging();
					this._MaHuyen = value;
					this.SendPropertyChanged("MaHuyen");
					this.OnMaHuyenChanged();
				}
			}
		}
		
		[Column(Storage="_MaTinh", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaTinh
		{
			get
			{
				return this._MaTinh;
			}
			set
			{
				if ((this._MaTinh != value))
				{
					if (this._tbTinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTinhChanging(value);
					this.SendPropertyChanging();
					this._MaTinh = value;
					this.SendPropertyChanged("MaTinh");
					this.OnMaTinhChanged();
				}
			}
		}
		
		[Column(Storage="_TenHuyen", DbType="NVarChar(100)")]
		public string TenHuyen
		{
			get
			{
				return this._TenHuyen;
			}
			set
			{
				if ((this._TenHuyen != value))
				{
					this.OnTenHuyenChanging(value);
					this.SendPropertyChanging();
					this._TenHuyen = value;
					this.SendPropertyChanged("TenHuyen");
					this.OnTenHuyenChanged();
				}
			}
		}
		
		[Association(Name="tbHuyen_tbXa", Storage="_tbXas", OtherKey="MaHuyen")]
		public EntitySet<tbXa> tbXas
		{
			get
			{
				return this._tbXas;
			}
			set
			{
				this._tbXas.Assign(value);
			}
		}
		
		[Association(Name="tbTinh_tbHuyen", Storage="_tbTinh", ThisKey="MaTinh", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbTinh tbTinh
		{
			get
			{
				return this._tbTinh.Entity;
			}
			set
			{
				tbTinh previousValue = this._tbTinh.Entity;
				if (((previousValue != value) 
							|| (this._tbTinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbTinh.Entity = null;
						previousValue.tbHuyens.Remove(this);
					}
					this._tbTinh.Entity = value;
					if ((value != null))
					{
						value.tbHuyens.Add(this);
						this._MaTinh = value.MaTinh;
					}
					else
					{
						this._MaTinh = default(string);
					}
					this.SendPropertyChanged("tbTinh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbXas(tbXa entity)
		{
			this.SendPropertyChanging();
			entity.tbHuyen = this;
		}
		
		private void detach_tbXas(tbXa entity)
		{
			this.SendPropertyChanging();
			entity.tbHuyen = null;
		}
	}
	
	[Table(Name="dbo.tbLopHoc")]
	public partial class tbLopHoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SoThuTu;
		
		private string _TenLop;
		
		private System.Nullable<int> _SoBuoiHoc;
		
		private string _MaTruong;
		
		private string _KhoiLop;
		
		private EntityRef<tbTruong> _tbTruong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoThuTuChanging(int value);
    partial void OnSoThuTuChanged();
    partial void OnTenLopChanging(string value);
    partial void OnTenLopChanged();
    partial void OnSoBuoiHocChanging(System.Nullable<int> value);
    partial void OnSoBuoiHocChanged();
    partial void OnMaTruongChanging(string value);
    partial void OnMaTruongChanged();
    partial void OnKhoiLopChanging(string value);
    partial void OnKhoiLopChanged();
    #endregion
		
		public tbLopHoc()
		{
			this._tbTruong = default(EntityRef<tbTruong>);
			OnCreated();
		}
		
		[Column(Storage="_SoThuTu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SoThuTu
		{
			get
			{
				return this._SoThuTu;
			}
			set
			{
				if ((this._SoThuTu != value))
				{
					this.OnSoThuTuChanging(value);
					this.SendPropertyChanging();
					this._SoThuTu = value;
					this.SendPropertyChanged("SoThuTu");
					this.OnSoThuTuChanged();
				}
			}
		}
		
		[Column(Storage="_TenLop", DbType="NVarChar(50)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this.OnTenLopChanging(value);
					this.SendPropertyChanging();
					this._TenLop = value;
					this.SendPropertyChanged("TenLop");
					this.OnTenLopChanged();
				}
			}
		}
		
		[Column(Storage="_SoBuoiHoc", DbType="Int")]
		public System.Nullable<int> SoBuoiHoc
		{
			get
			{
				return this._SoBuoiHoc;
			}
			set
			{
				if ((this._SoBuoiHoc != value))
				{
					this.OnSoBuoiHocChanging(value);
					this.SendPropertyChanging();
					this._SoBuoiHoc = value;
					this.SendPropertyChanged("SoBuoiHoc");
					this.OnSoBuoiHocChanged();
				}
			}
		}
		
		[Column(Storage="_MaTruong", DbType="NChar(10)")]
		public string MaTruong
		{
			get
			{
				return this._MaTruong;
			}
			set
			{
				if ((this._MaTruong != value))
				{
					if (this._tbTruong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTruongChanging(value);
					this.SendPropertyChanging();
					this._MaTruong = value;
					this.SendPropertyChanged("MaTruong");
					this.OnMaTruongChanged();
				}
			}
		}
		
		[Column(Storage="_KhoiLop", DbType="NChar(10)")]
		public string KhoiLop
		{
			get
			{
				return this._KhoiLop;
			}
			set
			{
				if ((this._KhoiLop != value))
				{
					this.OnKhoiLopChanging(value);
					this.SendPropertyChanging();
					this._KhoiLop = value;
					this.SendPropertyChanged("KhoiLop");
					this.OnKhoiLopChanged();
				}
			}
		}
		
		[Association(Name="tbTruong_tbLopHoc", Storage="_tbTruong", ThisKey="MaTruong", IsForeignKey=true)]
		public tbTruong tbTruong
		{
			get
			{
				return this._tbTruong.Entity;
			}
			set
			{
				tbTruong previousValue = this._tbTruong.Entity;
				if (((previousValue != value) 
							|| (this._tbTruong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbTruong.Entity = null;
						previousValue.tbLopHocs.Remove(this);
					}
					this._tbTruong.Entity = value;
					if ((value != null))
					{
						value.tbLopHocs.Add(this);
						this._MaTruong = value.MaTruong;
					}
					else
					{
						this._MaTruong = default(string);
					}
					this.SendPropertyChanged("tbTruong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.tbThanhVien")]
	public partial class tbThanhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaThanhVien;
		
		private string _MaHoGiaDinh;
		
		private string _TenThanhVien;
		
		private string _QuanHeVoiChuHo;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _GioiTinh;
		
		private string _GiaDinhChinhSach;
		
		private string _DanToc;
		
		private string _TrinhDo1;
		
		private string _TrinhDo2;
		
		private string _TrinhDo3;
		
		private string _TrinhDo4;
		
		private string _TrinhDo5;
		
		private string _NamTotNghiep;
		
		private string _NamBoHoc;
		
		private System.Nullable<System.DateTime> _NgayChuyenDen;
		
		private string _NoiKhac;
		
		private string _GhiChu;
		
		private string _TinhTrang;
		
		private string _TenTruong;
		
		private System.Nullable<System.DateTime> _NgayChuyenDi;
		
		private string _NoiChuyenDen;
		
		private EntityRef<tbChuHo> _tbChuHo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThanhVienChanging(int value);
    partial void OnMaThanhVienChanged();
    partial void OnMaHoGiaDinhChanging(string value);
    partial void OnMaHoGiaDinhChanged();
    partial void OnTenThanhVienChanging(string value);
    partial void OnTenThanhVienChanged();
    partial void OnQuanHeVoiChuHoChanging(string value);
    partial void OnQuanHeVoiChuHoChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnGiaDinhChinhSachChanging(string value);
    partial void OnGiaDinhChinhSachChanged();
    partial void OnDanTocChanging(string value);
    partial void OnDanTocChanged();
    partial void OnTrinhDo1Changing(string value);
    partial void OnTrinhDo1Changed();
    partial void OnTrinhDo2Changing(string value);
    partial void OnTrinhDo2Changed();
    partial void OnTrinhDo3Changing(string value);
    partial void OnTrinhDo3Changed();
    partial void OnTrinhDo4Changing(string value);
    partial void OnTrinhDo4Changed();
    partial void OnTrinhDo5Changing(string value);
    partial void OnTrinhDo5Changed();
    partial void OnNamTotNghiepChanging(string value);
    partial void OnNamTotNghiepChanged();
    partial void OnNamBoHocChanging(string value);
    partial void OnNamBoHocChanged();
    partial void OnNgayChuyenDenChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayChuyenDenChanged();
    partial void OnNoiKhacChanging(string value);
    partial void OnNoiKhacChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnTinhTrangChanging(string value);
    partial void OnTinhTrangChanged();
    partial void OnTenTruongChanging(string value);
    partial void OnTenTruongChanged();
    partial void OnNgayChuyenDiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayChuyenDiChanged();
    partial void OnNoiChuyenDenChanging(string value);
    partial void OnNoiChuyenDenChanged();
    #endregion
		
		public tbThanhVien()
		{
			this._tbChuHo = default(EntityRef<tbChuHo>);
			OnCreated();
		}
		
		[Column(Storage="_MaThanhVien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaThanhVien
		{
			get
			{
				return this._MaThanhVien;
			}
			set
			{
				if ((this._MaThanhVien != value))
				{
					this.OnMaThanhVienChanging(value);
					this.SendPropertyChanging();
					this._MaThanhVien = value;
					this.SendPropertyChanged("MaThanhVien");
					this.OnMaThanhVienChanged();
				}
			}
		}
		
		[Column(Storage="_MaHoGiaDinh", DbType="NChar(10)")]
		public string MaHoGiaDinh
		{
			get
			{
				return this._MaHoGiaDinh;
			}
			set
			{
				if ((this._MaHoGiaDinh != value))
				{
					if (this._tbChuHo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHoGiaDinhChanging(value);
					this.SendPropertyChanging();
					this._MaHoGiaDinh = value;
					this.SendPropertyChanged("MaHoGiaDinh");
					this.OnMaHoGiaDinhChanged();
				}
			}
		}
		
		[Column(Storage="_TenThanhVien", DbType="NVarChar(100)")]
		public string TenThanhVien
		{
			get
			{
				return this._TenThanhVien;
			}
			set
			{
				if ((this._TenThanhVien != value))
				{
					this.OnTenThanhVienChanging(value);
					this.SendPropertyChanging();
					this._TenThanhVien = value;
					this.SendPropertyChanged("TenThanhVien");
					this.OnTenThanhVienChanged();
				}
			}
		}
		
		[Column(Storage="_QuanHeVoiChuHo", DbType="NVarChar(50)")]
		public string QuanHeVoiChuHo
		{
			get
			{
				return this._QuanHeVoiChuHo;
			}
			set
			{
				if ((this._QuanHeVoiChuHo != value))
				{
					this.OnQuanHeVoiChuHoChanging(value);
					this.SendPropertyChanging();
					this._QuanHeVoiChuHo = value;
					this.SendPropertyChanged("QuanHeVoiChuHo");
					this.OnQuanHeVoiChuHoChanged();
				}
			}
		}
		
		[Column(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[Column(Storage="_GioiTinh", DbType="NVarChar(5)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[Column(Storage="_GiaDinhChinhSach", DbType="NVarChar(50)")]
		public string GiaDinhChinhSach
		{
			get
			{
				return this._GiaDinhChinhSach;
			}
			set
			{
				if ((this._GiaDinhChinhSach != value))
				{
					this.OnGiaDinhChinhSachChanging(value);
					this.SendPropertyChanging();
					this._GiaDinhChinhSach = value;
					this.SendPropertyChanged("GiaDinhChinhSach");
					this.OnGiaDinhChinhSachChanged();
				}
			}
		}
		
		[Column(Storage="_DanToc", DbType="NVarChar(50)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this.OnDanTocChanging(value);
					this.SendPropertyChanging();
					this._DanToc = value;
					this.SendPropertyChanged("DanToc");
					this.OnDanTocChanged();
				}
			}
		}
		
		[Column(Storage="_TrinhDo1", DbType="NVarChar(50)")]
		public string TrinhDo1
		{
			get
			{
				return this._TrinhDo1;
			}
			set
			{
				if ((this._TrinhDo1 != value))
				{
					this.OnTrinhDo1Changing(value);
					this.SendPropertyChanging();
					this._TrinhDo1 = value;
					this.SendPropertyChanged("TrinhDo1");
					this.OnTrinhDo1Changed();
				}
			}
		}
		
		[Column(Storage="_TrinhDo2", DbType="NVarChar(50)")]
		public string TrinhDo2
		{
			get
			{
				return this._TrinhDo2;
			}
			set
			{
				if ((this._TrinhDo2 != value))
				{
					this.OnTrinhDo2Changing(value);
					this.SendPropertyChanging();
					this._TrinhDo2 = value;
					this.SendPropertyChanged("TrinhDo2");
					this.OnTrinhDo2Changed();
				}
			}
		}
		
		[Column(Storage="_TrinhDo3", DbType="NVarChar(50)")]
		public string TrinhDo3
		{
			get
			{
				return this._TrinhDo3;
			}
			set
			{
				if ((this._TrinhDo3 != value))
				{
					this.OnTrinhDo3Changing(value);
					this.SendPropertyChanging();
					this._TrinhDo3 = value;
					this.SendPropertyChanged("TrinhDo3");
					this.OnTrinhDo3Changed();
				}
			}
		}
		
		[Column(Storage="_TrinhDo4", DbType="NVarChar(50)")]
		public string TrinhDo4
		{
			get
			{
				return this._TrinhDo4;
			}
			set
			{
				if ((this._TrinhDo4 != value))
				{
					this.OnTrinhDo4Changing(value);
					this.SendPropertyChanging();
					this._TrinhDo4 = value;
					this.SendPropertyChanged("TrinhDo4");
					this.OnTrinhDo4Changed();
				}
			}
		}
		
		[Column(Storage="_TrinhDo5", DbType="NVarChar(50)")]
		public string TrinhDo5
		{
			get
			{
				return this._TrinhDo5;
			}
			set
			{
				if ((this._TrinhDo5 != value))
				{
					this.OnTrinhDo5Changing(value);
					this.SendPropertyChanging();
					this._TrinhDo5 = value;
					this.SendPropertyChanged("TrinhDo5");
					this.OnTrinhDo5Changed();
				}
			}
		}
		
		[Column(Storage="_NamTotNghiep", DbType="NChar(10)")]
		public string NamTotNghiep
		{
			get
			{
				return this._NamTotNghiep;
			}
			set
			{
				if ((this._NamTotNghiep != value))
				{
					this.OnNamTotNghiepChanging(value);
					this.SendPropertyChanging();
					this._NamTotNghiep = value;
					this.SendPropertyChanged("NamTotNghiep");
					this.OnNamTotNghiepChanged();
				}
			}
		}
		
		[Column(Storage="_NamBoHoc", DbType="NChar(10)")]
		public string NamBoHoc
		{
			get
			{
				return this._NamBoHoc;
			}
			set
			{
				if ((this._NamBoHoc != value))
				{
					this.OnNamBoHocChanging(value);
					this.SendPropertyChanging();
					this._NamBoHoc = value;
					this.SendPropertyChanged("NamBoHoc");
					this.OnNamBoHocChanged();
				}
			}
		}
		
		[Column(Storage="_NgayChuyenDen", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayChuyenDen
		{
			get
			{
				return this._NgayChuyenDen;
			}
			set
			{
				if ((this._NgayChuyenDen != value))
				{
					this.OnNgayChuyenDenChanging(value);
					this.SendPropertyChanging();
					this._NgayChuyenDen = value;
					this.SendPropertyChanged("NgayChuyenDen");
					this.OnNgayChuyenDenChanged();
				}
			}
		}
		
		[Column(Storage="_NoiKhac", DbType="NVarChar(100)")]
		public string NoiKhac
		{
			get
			{
				return this._NoiKhac;
			}
			set
			{
				if ((this._NoiKhac != value))
				{
					this.OnNoiKhacChanging(value);
					this.SendPropertyChanging();
					this._NoiKhac = value;
					this.SendPropertyChanged("NoiKhac");
					this.OnNoiKhacChanged();
				}
			}
		}
		
		[Column(Storage="_GhiChu", DbType="NVarChar(150)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[Column(Storage="_TinhTrang", DbType="NVarChar(50)")]
		public string TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[Column(Storage="_TenTruong", DbType="NVarChar(100)")]
		public string TenTruong
		{
			get
			{
				return this._TenTruong;
			}
			set
			{
				if ((this._TenTruong != value))
				{
					this.OnTenTruongChanging(value);
					this.SendPropertyChanging();
					this._TenTruong = value;
					this.SendPropertyChanged("TenTruong");
					this.OnTenTruongChanged();
				}
			}
		}
		
		[Column(Storage="_NgayChuyenDi", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayChuyenDi
		{
			get
			{
				return this._NgayChuyenDi;
			}
			set
			{
				if ((this._NgayChuyenDi != value))
				{
					this.OnNgayChuyenDiChanging(value);
					this.SendPropertyChanging();
					this._NgayChuyenDi = value;
					this.SendPropertyChanged("NgayChuyenDi");
					this.OnNgayChuyenDiChanged();
				}
			}
		}
		
		[Column(Storage="_NoiChuyenDen", DbType="NVarChar(100)")]
		public string NoiChuyenDen
		{
			get
			{
				return this._NoiChuyenDen;
			}
			set
			{
				if ((this._NoiChuyenDen != value))
				{
					this.OnNoiChuyenDenChanging(value);
					this.SendPropertyChanging();
					this._NoiChuyenDen = value;
					this.SendPropertyChanged("NoiChuyenDen");
					this.OnNoiChuyenDenChanged();
				}
			}
		}
		
		[Association(Name="tbChuHo_tbThanhVien", Storage="_tbChuHo", ThisKey="MaHoGiaDinh", IsForeignKey=true)]
		public tbChuHo tbChuHo
		{
			get
			{
				return this._tbChuHo.Entity;
			}
			set
			{
				tbChuHo previousValue = this._tbChuHo.Entity;
				if (((previousValue != value) 
							|| (this._tbChuHo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbChuHo.Entity = null;
						previousValue.tbThanhViens.Remove(this);
					}
					this._tbChuHo.Entity = value;
					if ((value != null))
					{
						value.tbThanhViens.Add(this);
						this._MaHoGiaDinh = value.MaHoGiaDinh;
					}
					else
					{
						this._MaHoGiaDinh = default(string);
					}
					this.SendPropertyChanged("tbChuHo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.tbThonXom")]
	public partial class tbThonXom : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaThon;
		
		private string _TenThon;
		
		private string _MaXa;
		
		private EntitySet<tbChuHo> _tbChuHos;
		
		private EntityRef<tbXa> _tbXa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThonChanging(string value);
    partial void OnMaThonChanged();
    partial void OnTenThonChanging(string value);
    partial void OnTenThonChanged();
    partial void OnMaXaChanging(string value);
    partial void OnMaXaChanged();
    #endregion
		
		public tbThonXom()
		{
			this._tbChuHos = new EntitySet<tbChuHo>(new Action<tbChuHo>(this.attach_tbChuHos), new Action<tbChuHo>(this.detach_tbChuHos));
			this._tbXa = default(EntityRef<tbXa>);
			OnCreated();
		}
		
		[Column(Storage="_MaThon", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaThon
		{
			get
			{
				return this._MaThon;
			}
			set
			{
				if ((this._MaThon != value))
				{
					this.OnMaThonChanging(value);
					this.SendPropertyChanging();
					this._MaThon = value;
					this.SendPropertyChanged("MaThon");
					this.OnMaThonChanged();
				}
			}
		}
		
		[Column(Storage="_TenThon", DbType="NVarChar(100)")]
		public string TenThon
		{
			get
			{
				return this._TenThon;
			}
			set
			{
				if ((this._TenThon != value))
				{
					this.OnTenThonChanging(value);
					this.SendPropertyChanging();
					this._TenThon = value;
					this.SendPropertyChanged("TenThon");
					this.OnTenThonChanged();
				}
			}
		}
		
		[Column(Storage="_MaXa", DbType="NChar(10)")]
		public string MaXa
		{
			get
			{
				return this._MaXa;
			}
			set
			{
				if ((this._MaXa != value))
				{
					if (this._tbXa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaXaChanging(value);
					this.SendPropertyChanging();
					this._MaXa = value;
					this.SendPropertyChanged("MaXa");
					this.OnMaXaChanged();
				}
			}
		}
		
		[Association(Name="tbThonXom_tbChuHo", Storage="_tbChuHos", OtherKey="MaThon")]
		public EntitySet<tbChuHo> tbChuHos
		{
			get
			{
				return this._tbChuHos;
			}
			set
			{
				this._tbChuHos.Assign(value);
			}
		}
		
		[Association(Name="tbXa_tbThonXom", Storage="_tbXa", ThisKey="MaXa", IsForeignKey=true)]
		public tbXa tbXa
		{
			get
			{
				return this._tbXa.Entity;
			}
			set
			{
				tbXa previousValue = this._tbXa.Entity;
				if (((previousValue != value) 
							|| (this._tbXa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbXa.Entity = null;
						previousValue.tbThonXoms.Remove(this);
					}
					this._tbXa.Entity = value;
					if ((value != null))
					{
						value.tbThonXoms.Add(this);
						this._MaXa = value.MaXa;
					}
					else
					{
						this._MaXa = default(string);
					}
					this.SendPropertyChanged("tbXa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbChuHos(tbChuHo entity)
		{
			this.SendPropertyChanging();
			entity.tbThonXom = this;
		}
		
		private void detach_tbChuHos(tbChuHo entity)
		{
			this.SendPropertyChanging();
			entity.tbThonXom = null;
		}
	}
	
	[Table(Name="dbo.tbTinh")]
	public partial class tbTinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTinh;
		
		private string _TenTinh;
		
		private EntitySet<tbHuyen> _tbHuyens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTinhChanging(string value);
    partial void OnMaTinhChanged();
    partial void OnTenTinhChanging(string value);
    partial void OnTenTinhChanged();
    #endregion
		
		public tbTinh()
		{
			this._tbHuyens = new EntitySet<tbHuyen>(new Action<tbHuyen>(this.attach_tbHuyens), new Action<tbHuyen>(this.detach_tbHuyens));
			OnCreated();
		}
		
		[Column(Storage="_MaTinh", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTinh
		{
			get
			{
				return this._MaTinh;
			}
			set
			{
				if ((this._MaTinh != value))
				{
					this.OnMaTinhChanging(value);
					this.SendPropertyChanging();
					this._MaTinh = value;
					this.SendPropertyChanged("MaTinh");
					this.OnMaTinhChanged();
				}
			}
		}
		
		[Column(Storage="_TenTinh", DbType="NVarChar(50)")]
		public string TenTinh
		{
			get
			{
				return this._TenTinh;
			}
			set
			{
				if ((this._TenTinh != value))
				{
					this.OnTenTinhChanging(value);
					this.SendPropertyChanging();
					this._TenTinh = value;
					this.SendPropertyChanged("TenTinh");
					this.OnTenTinhChanged();
				}
			}
		}
		
		[Association(Name="tbTinh_tbHuyen", Storage="_tbHuyens", OtherKey="MaTinh")]
		public EntitySet<tbHuyen> tbHuyens
		{
			get
			{
				return this._tbHuyens;
			}
			set
			{
				this._tbHuyens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbHuyens(tbHuyen entity)
		{
			this.SendPropertyChanging();
			entity.tbTinh = this;
		}
		
		private void detach_tbHuyens(tbHuyen entity)
		{
			this.SendPropertyChanging();
			entity.tbTinh = null;
		}
	}
	
	[Table(Name="dbo.tbTruong")]
	public partial class tbTruong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTruong;
		
		private string _MaXa;
		
		private string _TenTruong;
		
		private string _TenHieuTruong;
		
		private EntitySet<tbCSVC> _tbCSVCs;
		
		private EntitySet<tbGiaoVien> _tbGiaoViens;
		
		private EntitySet<tbLopHoc> _tbLopHocs;
		
		private EntityRef<tbXa> _tbXa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTruongChanging(string value);
    partial void OnMaTruongChanged();
    partial void OnMaXaChanging(string value);
    partial void OnMaXaChanged();
    partial void OnTenTruongChanging(string value);
    partial void OnTenTruongChanged();
    partial void OnTenHieuTruongChanging(string value);
    partial void OnTenHieuTruongChanged();
    #endregion
		
		public tbTruong()
		{
			this._tbCSVCs = new EntitySet<tbCSVC>(new Action<tbCSVC>(this.attach_tbCSVCs), new Action<tbCSVC>(this.detach_tbCSVCs));
			this._tbGiaoViens = new EntitySet<tbGiaoVien>(new Action<tbGiaoVien>(this.attach_tbGiaoViens), new Action<tbGiaoVien>(this.detach_tbGiaoViens));
			this._tbLopHocs = new EntitySet<tbLopHoc>(new Action<tbLopHoc>(this.attach_tbLopHocs), new Action<tbLopHoc>(this.detach_tbLopHocs));
			this._tbXa = default(EntityRef<tbXa>);
			OnCreated();
		}
		
		[Column(Storage="_MaTruong", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTruong
		{
			get
			{
				return this._MaTruong;
			}
			set
			{
				if ((this._MaTruong != value))
				{
					this.OnMaTruongChanging(value);
					this.SendPropertyChanging();
					this._MaTruong = value;
					this.SendPropertyChanged("MaTruong");
					this.OnMaTruongChanged();
				}
			}
		}
		
		[Column(Storage="_MaXa", DbType="NChar(10)")]
		public string MaXa
		{
			get
			{
				return this._MaXa;
			}
			set
			{
				if ((this._MaXa != value))
				{
					if (this._tbXa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaXaChanging(value);
					this.SendPropertyChanging();
					this._MaXa = value;
					this.SendPropertyChanged("MaXa");
					this.OnMaXaChanged();
				}
			}
		}
		
		[Column(Storage="_TenTruong", DbType="NVarChar(150)")]
		public string TenTruong
		{
			get
			{
				return this._TenTruong;
			}
			set
			{
				if ((this._TenTruong != value))
				{
					this.OnTenTruongChanging(value);
					this.SendPropertyChanging();
					this._TenTruong = value;
					this.SendPropertyChanged("TenTruong");
					this.OnTenTruongChanged();
				}
			}
		}
		
		[Column(Storage="_TenHieuTruong", DbType="NVarChar(100)")]
		public string TenHieuTruong
		{
			get
			{
				return this._TenHieuTruong;
			}
			set
			{
				if ((this._TenHieuTruong != value))
				{
					this.OnTenHieuTruongChanging(value);
					this.SendPropertyChanging();
					this._TenHieuTruong = value;
					this.SendPropertyChanged("TenHieuTruong");
					this.OnTenHieuTruongChanged();
				}
			}
		}
		
		[Association(Name="tbTruong_tbCSVC", Storage="_tbCSVCs", OtherKey="MaTruong")]
		public EntitySet<tbCSVC> tbCSVCs
		{
			get
			{
				return this._tbCSVCs;
			}
			set
			{
				this._tbCSVCs.Assign(value);
			}
		}
		
		[Association(Name="tbTruong_tbGiaoVien", Storage="_tbGiaoViens", OtherKey="MaTruong")]
		public EntitySet<tbGiaoVien> tbGiaoViens
		{
			get
			{
				return this._tbGiaoViens;
			}
			set
			{
				this._tbGiaoViens.Assign(value);
			}
		}
		
		[Association(Name="tbTruong_tbLopHoc", Storage="_tbLopHocs", OtherKey="MaTruong")]
		public EntitySet<tbLopHoc> tbLopHocs
		{
			get
			{
				return this._tbLopHocs;
			}
			set
			{
				this._tbLopHocs.Assign(value);
			}
		}
		
		[Association(Name="tbXa_tbTruong", Storage="_tbXa", ThisKey="MaXa", IsForeignKey=true)]
		public tbXa tbXa
		{
			get
			{
				return this._tbXa.Entity;
			}
			set
			{
				tbXa previousValue = this._tbXa.Entity;
				if (((previousValue != value) 
							|| (this._tbXa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbXa.Entity = null;
						previousValue.tbTruongs.Remove(this);
					}
					this._tbXa.Entity = value;
					if ((value != null))
					{
						value.tbTruongs.Add(this);
						this._MaXa = value.MaXa;
					}
					else
					{
						this._MaXa = default(string);
					}
					this.SendPropertyChanged("tbXa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbCSVCs(tbCSVC entity)
		{
			this.SendPropertyChanging();
			entity.tbTruong = this;
		}
		
		private void detach_tbCSVCs(tbCSVC entity)
		{
			this.SendPropertyChanging();
			entity.tbTruong = null;
		}
		
		private void attach_tbGiaoViens(tbGiaoVien entity)
		{
			this.SendPropertyChanging();
			entity.tbTruong = this;
		}
		
		private void detach_tbGiaoViens(tbGiaoVien entity)
		{
			this.SendPropertyChanging();
			entity.tbTruong = null;
		}
		
		private void attach_tbLopHocs(tbLopHoc entity)
		{
			this.SendPropertyChanging();
			entity.tbTruong = this;
		}
		
		private void detach_tbLopHocs(tbLopHoc entity)
		{
			this.SendPropertyChanging();
			entity.tbTruong = null;
		}
	}
	
	[Table(Name="dbo.tbXa")]
	public partial class tbXa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaXa;
		
		private string _MaHuyen;
		
		private string _TenXa;
		
		private EntitySet<tbThonXom> _tbThonXoms;
		
		private EntitySet<tbTruong> _tbTruongs;
		
		private EntityRef<tbHuyen> _tbHuyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaXaChanging(string value);
    partial void OnMaXaChanged();
    partial void OnMaHuyenChanging(string value);
    partial void OnMaHuyenChanged();
    partial void OnTenXaChanging(string value);
    partial void OnTenXaChanged();
    #endregion
		
		public tbXa()
		{
			this._tbThonXoms = new EntitySet<tbThonXom>(new Action<tbThonXom>(this.attach_tbThonXoms), new Action<tbThonXom>(this.detach_tbThonXoms));
			this._tbTruongs = new EntitySet<tbTruong>(new Action<tbTruong>(this.attach_tbTruongs), new Action<tbTruong>(this.detach_tbTruongs));
			this._tbHuyen = default(EntityRef<tbHuyen>);
			OnCreated();
		}
		
		[Column(Storage="_MaXa", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaXa
		{
			get
			{
				return this._MaXa;
			}
			set
			{
				if ((this._MaXa != value))
				{
					this.OnMaXaChanging(value);
					this.SendPropertyChanging();
					this._MaXa = value;
					this.SendPropertyChanged("MaXa");
					this.OnMaXaChanged();
				}
			}
		}
		
		[Column(Storage="_MaHuyen", DbType="NChar(10)")]
		public string MaHuyen
		{
			get
			{
				return this._MaHuyen;
			}
			set
			{
				if ((this._MaHuyen != value))
				{
					if (this._tbHuyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHuyenChanging(value);
					this.SendPropertyChanging();
					this._MaHuyen = value;
					this.SendPropertyChanged("MaHuyen");
					this.OnMaHuyenChanged();
				}
			}
		}
		
		[Column(Storage="_TenXa", DbType="NVarChar(100)")]
		public string TenXa
		{
			get
			{
				return this._TenXa;
			}
			set
			{
				if ((this._TenXa != value))
				{
					this.OnTenXaChanging(value);
					this.SendPropertyChanging();
					this._TenXa = value;
					this.SendPropertyChanged("TenXa");
					this.OnTenXaChanged();
				}
			}
		}
		
		[Association(Name="tbXa_tbThonXom", Storage="_tbThonXoms", OtherKey="MaXa")]
		public EntitySet<tbThonXom> tbThonXoms
		{
			get
			{
				return this._tbThonXoms;
			}
			set
			{
				this._tbThonXoms.Assign(value);
			}
		}
		
		[Association(Name="tbXa_tbTruong", Storage="_tbTruongs", OtherKey="MaXa")]
		public EntitySet<tbTruong> tbTruongs
		{
			get
			{
				return this._tbTruongs;
			}
			set
			{
				this._tbTruongs.Assign(value);
			}
		}
		
		[Association(Name="tbHuyen_tbXa", Storage="_tbHuyen", ThisKey="MaHuyen", IsForeignKey=true)]
		public tbHuyen tbHuyen
		{
			get
			{
				return this._tbHuyen.Entity;
			}
			set
			{
				tbHuyen previousValue = this._tbHuyen.Entity;
				if (((previousValue != value) 
							|| (this._tbHuyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbHuyen.Entity = null;
						previousValue.tbXas.Remove(this);
					}
					this._tbHuyen.Entity = value;
					if ((value != null))
					{
						value.tbXas.Add(this);
						this._MaHuyen = value.MaHuyen;
					}
					else
					{
						this._MaHuyen = default(string);
					}
					this.SendPropertyChanged("tbHuyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbThonXoms(tbThonXom entity)
		{
			this.SendPropertyChanging();
			entity.tbXa = this;
		}
		
		private void detach_tbThonXoms(tbThonXom entity)
		{
			this.SendPropertyChanging();
			entity.tbXa = null;
		}
		
		private void attach_tbTruongs(tbTruong entity)
		{
			this.SendPropertyChanging();
			entity.tbXa = this;
		}
		
		private void detach_tbTruongs(tbTruong entity)
		{
			this.SendPropertyChanging();
			entity.tbXa = null;
		}
	}
}
#pragma warning restore 1591
